---
- name: Ping all hosts to verify connectivity
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Test connection to all hosts
      ping:
      register: ping_result
      
    - name: Display ping results
      debug:
        msg: "Host {{ inventory_hostname }} is reachable"
      when: ping_result is succeeded
      
    - name: Show unreachable hosts
      debug:
        msg: "Host {{ inventory_hostname }} is NOT reachable"
      when: ping_result is failed